server.servlet.context-path=/BMPAYInternet
server.port=8080

#UAT Server
#intranetconnection=https://BIPSBTWTDDB301.bankofbaroda.co.in:8443/Bipsportal

#Production Server
#intranetconnection=http://172.17.42.218:8443/Bipsportal

#Local Server
intranetconnection=http://localhost:8444/Bipsportal
# JWT Configuration
jwt.secret=your-very-long-secret-key-minimum-32-characters
jwt.expiration=86400000   
# 24 hours in milliseconds